export const MOCK_USER_CUSTOMER = {
    id: 'mock-customer-123',
    uid: 'mock-customer-123',
    email: 'customer@taskmate.com',
    full_name: 'Diekolere Olaitan',
    displayName: 'Diekolere Olaitan',
    role: 'customer',
    avatar_url: 'https://i.pravatar.cc/150?u=customer',
    photoURL: 'https://i.pravatar.cc/150?u=customer',
    location_name: 'Lekki Phase 1, Lagos',
    trust_score: 85,
    is_active: true,
    saved_workers: ['mock-provider-1']
};

export const MOCK_USER_PROVIDER = {
    id: 'mock-provider-1',
    uid: 'mock-provider-1',
    email: 'provider@taskmate.com',
    full_name: 'Ibrahim Musa',
    displayName: 'Ibrahim Musa',
    role: 'provider',
    avatar_url: 'https://i.pravatar.cc/150?u=provider',
    photoURL: 'https://i.pravatar.cc/150?u=provider',
    location_name: 'Surulere, Lagos',
    phone_number: '+234-801-234-5678',
    trust_score: 92,
    is_active: true,
    kycCompleted: true,
    bvnVerified: true,
    bankName: 'Zenith Bank',
    accountNumber: '2087654321',
    accountName: 'Ibrahim Musa',
    provider_profiles: {
        trade_category: ['electrician', 'plumber'],
        bio: 'Certified electrician with 10 years experience in residential wiring.',
        years_experience: 10,
        hourly_rate_min: 5000,
        hourly_rate_max: 15000,
        verification_status: 'verified',
        average_rating: 4.8,
        completed_jobs_count: 124
    }
};

export const MOCK_JOBS = [
    {
        id: 'job-paid-01',
        customer_id: 'mock-customer-123',
        worker_id: 'mock-provider-1',
        providerId: 'mock-provider-1',
        title: 'Fix Kitchen Sink Pipes',
        description: 'The kitchen sink pipes are badly corroded and leaking. Customer needs full replacement of the P-trap and connecting pipes.',
        category: 'Plumbing',
        status: 'payment_secured',
        agreedPrice: 14500,
        budget_estimate: 15000,
        location: 'Ikeja GRA, Lagos',
        location_name: 'Ikeja GRA',
        customerName: 'Adaeze Okonkwo',
        urgency: 'high',
        images: [
            'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
            'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
        ],
        created_at: new Date(Date.now() - 7200000).toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'demo-001',
        customer_id: 'mock-customer-123',
        worker_id: 'mock-provider-1',
        title: 'Fix Bathroom Plumbing',
        description: 'Pipes under the bathroom sink are leaking and need urgent attention. Water is pooling on the floor.',
        category: 'Plumbing',
        status: 'negotiating',
        budget_estimate: 12000,
        location: 'Lekki Phase 1, Lagos',
        location_name: 'Lekki Phase 1',
        customerName: 'Diekolere Olaitan',
        urgency: 'high',
        agreedPrice: 11000,
        created_at: new Date(Date.now() - 3600000).toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'job-1',
        customer_id: 'mock-customer-123',
        worker_id: 'mock-provider-1',
        title: 'Fix Kitchen Sink Leak',
        description: 'The pipe under the kitchen sink is leaking heavily. Water is pooling under the cabinet and needs urgent attention before it causes more damage.',
        category: 'Plumbing',
        status: 'in_progress',
        budget_estimate: 8500,
        location: 'Lekki Phase 1, Lagos',
        location_name: 'Lekki Phase 1',
        customerName: 'Diekolere Olaitan',
        urgency: 'high',
        created_at: new Date(Date.now() - 86400000).toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: 'job-2',
        customer_id: 'mock-customer-456',
        worker_id: null,
        title: 'Install Ceiling Fan',
        description: 'Need a professional to install 3 ceiling fans in the living room and two bedrooms. All fans have already been purchased.',
        category: 'Electrical',
        status: 'Open',
        budget_estimate: 12000,
        location: 'Ikeja GRA, Lagos',
        location_name: 'Ikeja GRA',
        customerName: 'Emeka Nwosu',
        urgency: 'medium',
        created_at: new Date(Date.now() - 7200000).toISOString(),
        updated_at: new Date(Date.now() - 7200000).toISOString()
    },
    {
        id: 'job-3',
        customer_id: 'mock-customer-123',
        worker_id: 'mock-provider-2',
        title: 'A/C Servicing',
        description: 'Annual servicing for 4 split AC units across the flat.',
        category: 'HVAC',
        status: 'completed',
        budget_estimate: 25000,
        final_amount: 25000,
        location: 'Lekki Phase 1, Lagos',
        location_name: 'Lekki Phase 1',
        customerName: 'Diekolere Olaitan',
        created_at: new Date(Date.now() - 604800000).toISOString(),
        updated_at: new Date(Date.now() - 518400000).toISOString()
    },
    {
        id: 'job-4',
        customer_id: 'mock-customer-789',
        worker_id: null,
        title: 'Deep Clean 4-Bedroom Apartment',
        description: 'Moving into a new apartment and need a thorough deep clean of all rooms, kitchen, and bathrooms before move-in day.',
        category: 'Cleaning',
        status: 'Open',
        budget_estimate: 18000,
        location: 'Victoria Island, Lagos',
        location_name: 'Victoria Island',
        customerName: 'Ngozi Adeyemi',
        urgency: 'low',
        scheduledDate: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
        images: [
            'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
            'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
            'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
        ],
        created_at: new Date(Date.now() - 3600000).toISOString(),
        updated_at: new Date(Date.now() - 3600000).toISOString()
    },
    {
        id: 'job-5',
        customer_id: 'mock-customer-321',
        worker_id: null,
        title: 'Repair Wooden Wardrobe',
        description: 'The wardrobe door hinge is broken and two shelves have collapsed. Need a skilled carpenter to fix and reinforce it.',
        category: 'Carpentry',
        status: 'Open',
        budget_estimate: 9500,
        location: 'Yaba, Lagos',
        location_name: 'Yaba',
        customerName: 'Tunde Bakare',
        urgency: 'medium',
        created_at: new Date(Date.now() - 10800000).toISOString(),
        updated_at: new Date(Date.now() - 10800000).toISOString()
    },
];

export const MOCK_PROVIDERS = [
    {
        id: 'mock-provider-1',
        full_name: 'Ibrahim Musa',
        displayName: 'Ibrahim Musa',
        avatar_url: 'https://i.pravatar.cc/150?u=p1',
        phone_number: '+234-801-234-5678',
        role: 'provider',
        trust_score: 92,
        is_active: true,
        provider_profiles: {
            trade_category: ['electrician'],
            verification_status: 'verified',
            average_rating: 4.8,
            completed_jobs_count: 124,
            hourly_rate_min: 5000
        }
    },
    {
        id: 'mock-provider-2',
        full_name: 'Sarah Chen',
        displayName: 'Sarah Chen',
        avatar_url: 'https://i.pravatar.cc/150?u=p2',
        phone_number: '+234-802-345-6789',
        role: 'provider',
        trust_score: 88,
        is_active: true,
        provider_profiles: {
            trade_category: ['ac technician'],
            verification_status: 'verified',
            average_rating: 4.6,
            completed_jobs_count: 89,
            hourly_rate_min: 7000
        }
    },
    {
        id: 'mock-provider-3',
        full_name: 'Babatunde Raji',
        displayName: 'Babatunde Raji',
        avatar_url: 'https://i.pravatar.cc/150?u=p3',
        phone_number: '+234-803-456-7890',
        role: 'provider',
        trust_score: 95,
        is_active: true,
        provider_profiles: {
            trade_category: ['plumber'],
            verification_status: 'verified',
            average_rating: 4.9,
            completed_jobs_count: 210,
            hourly_rate_min: 6000
        }
    }
];
