import React, { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';
import Sidebar from '../../components/layout/Sidebar';
import TopNavbar from '../../components/layout/TopNavbar';
import MobileNavBar from '../../components/layout/MobileNavBar';

const COMMISSION_RATE = 0.1;
const AUTO_RELEASE_HOURS = 48;
const DEMO_SECONDS_LEFT = AUTO_RELEASE_HOURS * 3600 - 15;

const DISPUTE_CATEGORIES = [
    'Work not completed',
    'Poor quality of work',
    'Provider did not show up',
    'Safety concern',
    'Other',
];

// AI-guided questions per dispute category
const GUIDED_QUESTIONS = {
    'Work not completed': [
        'Which specific parts of the job were not finished?',
        'Did the provider leave the site before completing all tasks?',
        'Was an estimated completion time agreed upon beforehand?',
    ],
    'Poor quality of work': [
        'What specifically does not meet the expected standard?',
        'Is the issue something that could be fixed quickly, or is it a fundamental problem?',
        'Did you point out the issue to the provider while they were on-site?',
    ],
    'Provider did not show up': [
        'Did you receive any communication from the provider before the scheduled time?',
        'How long did you wait at the location?',
        'Has the provider given any explanation since then?',
    ],
    'Safety concern': [
        'What was the nature of the safety issue?',
        'Was anyone hurt or was property damaged?',
        'Did you report this to any other authority?',
    ],
    'Other': [
        'Please describe what went wrong in your own words.',
        'When did the issue first occur?',
        'What outcome would you consider a fair resolution?',
    ],
};

// Generate an AI summary from the answers
const buildSummary = (category, answers, hasPhotos) => {
    const answered = Object.entries(answers).filter(([, v]) => v.trim());
    const detail = answered.map(([q, a]) => `• ${q}\n  "${a}"`).join('\n\n');
    return `Dispute Category: ${category}

Guided Evidence Summary:
${detail || '(No details provided)'}

Photo Evidence: ${hasPhotos ? 'Yes — attached by customer' : 'None provided'}

Auto-generated by TaskMate Dispute Assistant.`;
};

const ConfirmCompletion = () => {
    const { jobId } = useParams();
    const navigate = useNavigate();

    const amount = 15000;
    const commission = Math.round(amount * COMMISSION_RATE);
    const providerReceives = amount - commission;

    const [secondsLeft, setSecondsLeft] = useState(DEMO_SECONDS_LEFT);
    const [phase, setPhase] = useState('pending');
    const [disputeReason, setDisputeReason] = useState('');
    const [disputeCategory, setDisputeCategory] = useState(DISPUTE_CATEGORIES[0]);
    const [categoryOpen, setCategoryOpen] = useState(false);

    // AI Dispute Assistant state
    const [disputeStep, setDisputeStep] = useState(0); // 0=category, 1=questions, 2=photos, 3=summary
    const [answers, setAnswers] = useState({});
    const [generatingSummary, setGeneratingSummary] = useState(false);
    const [generatedSummary, setGeneratedSummary] = useState('');
    const [hasPhotos, setHasPhotos] = useState(false);
    const [evidenceFile, setEvidenceFile] = useState(null);
    const [evidencePreview, setEvidencePreview] = useState(null);
    const evidenceRef = useRef();

    useEffect(() => {
        if (phase !== 'pending') return;
        const t = setInterval(() => setSecondsLeft(s => Math.max(0, s - 1)), 1000);
        return () => clearInterval(t);
    }, [phase]);

    const hours = Math.floor(secondsLeft / 3600);
    const mins = Math.floor((secondsLeft % 3600) / 60);
    const secs = secondsLeft % 60;
    const pad = (n) => String(n).padStart(2, '0');

    const releasePercent = Math.round(((DEMO_SECONDS_LEFT - secondsLeft) / DEMO_SECONDS_LEFT) * 100);

    const handleRelease = () => {
        setPhase('released');
        toast.success('Payment released to provider!');
        setTimeout(() => navigate('/customer/dashboard'), 3000);
    };

    const handleDispute = () => {
        setPhase('disputed');
        toast.success('Dispute submitted. Our team will review within 24 hours.');
        setTimeout(() => navigate('/customer/dashboard'), 3000);
    };

    const handleGenerateSummary = async () => {
        setGeneratingSummary(true);
        await new Promise(r => setTimeout(r, 1500));
        setGeneratedSummary(buildSummary(disputeCategory, answers, hasPhotos));
        setGeneratingSummary(false);
        setDisputeStep(3);
    };

    const handleEvidenceChange = (e) => {
        const f = e.target.files?.[0];
        if (!f) return;
        setEvidenceFile(f);
        setEvidencePreview(URL.createObjectURL(f));
        setHasPhotos(true);
    };

    return (
        <div className="flex min-h-screen bg-white font-sans text-gray-900">
            <Sidebar />
            <div className="flex-1 flex flex-col min-w-0">
                <TopNavbar breadcrumbs={['Customer', 'My Requests', 'Confirm Completion']} />

                <main className="flex-1 overflow-y-auto bg-white pb-24 md:pb-0">
                    <div className="max-w-2xl mx-auto px-4 py-10 sm:py-14">

                        <AnimatePresence mode="wait">

                            {phase === 'released' && (
                                <motion.div key="released" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="text-center py-20">
                                    <div className="w-20 h-20 bg-[#10B981] rounded-full flex items-center justify-center mx-auto mb-6 shadow-lg shadow-[#10B981]/30">
                                        <span className="material-icons text-white text-4xl">payments</span>
                                    </div>
                                    <h2 className="text-2xl font-bold text-gray-900 mb-2">Payment Released</h2>
                                    <p className="text-gray-500">₦{providerReceives.toLocaleString()} has been sent to your provider. Thanks for using TaskMate!</p>
                                </motion.div>
                            )}

                            {phase === 'disputed' && (
                                <motion.div key="disputed" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="text-center py-20">
                                    <div className="w-20 h-20 bg-amber-100 rounded-full flex items-center justify-center mx-auto mb-6">
                                        <span className="material-icons text-amber-600 text-4xl">gavel</span>
                                    </div>
                                    <h2 className="text-2xl font-bold text-gray-900 mb-2">Dispute Submitted</h2>
                                    <p className="text-gray-500 max-w-sm mx-auto">Our team will review your case within 24 hours. Payment is held until resolved.</p>
                                </motion.div>
                            )}

                            {phase === 'pending' && (
                                <motion.div key="pending" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="space-y-5">

                                    {/* Header */}
                                    <div className="text-center mb-8">
                                        <div className="w-16 h-16 bg-[#10B981]/10 rounded-2xl flex items-center justify-center mx-auto mb-4">
                                            <svg viewBox="0 0 24 24" fill="none" stroke="#10B981" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" className="w-8 h-8">
                                                <path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z" />
                                                <path d="M7.5 12l3 3 6-6" />
                                            </svg>
                                        </div>
                                        <h2 className="text-xl font-bold text-gray-900">Provider marked job complete</h2>
                                        <p className="text-sm text-gray-400 mt-1">Review and release payment, or raise a dispute if there's an issue.</p>
                                    </div>

                                    {/* Auto-release countdown */}
                                    <div className="bg-[#0F172A] rounded-2xl p-6 text-white">
                                        <div className="flex items-center justify-between mb-4">
                                            <div>
                                                <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-0.5">Auto-release in</p>
                                                <div className="flex items-baseline gap-1">
                                                    <span className="text-3xl font-black font-mono tabular-nums">{pad(hours)}:{pad(mins)}:{pad(secs)}</span>
                                                </div>
                                            </div>
                                            <div className="w-14 h-14 relative">
                                                <svg viewBox="0 0 36 36" className="w-full h-full -rotate-90">
                                                    <circle cx="18" cy="18" r="15.9" fill="none" stroke="#1e293b" strokeWidth="3" />
                                                    <circle cx="18" cy="18" r="15.9" fill="none" stroke="#10B981" strokeWidth="3"
                                                        strokeDasharray={`${releasePercent} ${100 - releasePercent}`}
                                                        strokeLinecap="round"
                                                    />
                                                </svg>
                                                <span className="absolute inset-0 flex items-center justify-center text-[10px] font-bold text-slate-400">{releasePercent}%</span>
                                            </div>
                                        </div>
                                        <p className="text-xs text-slate-400 leading-relaxed">
                                            Payment releases automatically after {AUTO_RELEASE_HOURS} hours if no dispute is raised. You can release early by tapping the button below.
                                        </p>
                                    </div>

                                    {/* Payment breakdown */}
                                    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
                                        <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-4">Payment Breakdown</p>
                                        <div className="space-y-3">
                                            <div className="flex justify-between text-sm">
                                                <span className="text-gray-500">Amount held in escrow</span>
                                                <span className="font-bold text-gray-900">₦{amount.toLocaleString()}</span>
                                            </div>
                                            <div className="flex justify-between text-sm text-gray-400">
                                                <span>Platform commission (10%)</span>
                                                <span>− ₦{commission.toLocaleString()}</span>
                                            </div>
                                            <div className="flex justify-between text-sm pt-3 border-t border-gray-100">
                                                <span className="font-bold text-gray-900">Provider receives</span>
                                                <span className="font-bold text-[#10B981] text-base">₦{providerReceives.toLocaleString()}</span>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Release early CTA */}
                                    <button
                                        onClick={handleRelease}
                                        className="w-full py-4 bg-[#10B981] hover:bg-[#059669] text-white font-bold rounded-xl text-sm transition-all shadow-md shadow-[#10B981]/20 flex items-center justify-center gap-2"
                                    >
                                        <span className="material-icons text-base">send</span>
                                        Release Payment Now
                                    </button>

                                    {/* Dispute section */}
                                    {phase !== 'dispute' && (
                                        <button
                                            onClick={() => setPhase('dispute')}
                                            className="w-full py-3 border border-red-200 bg-red-50 hover:bg-red-100 text-sm font-semibold text-red-600 rounded-xl transition-colors flex items-center justify-center gap-2"
                                        >
                                            <span className="material-icons text-base">flag</span>
                                            Something went wrong — Raise a Dispute
                                        </button>
                                    )}

                                </motion.div>
                            )}

                            {phase === 'dispute' && (
                                <motion.div key="dispute" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="space-y-5">

                                    {/* Header */}
                                    <div className="flex items-center gap-3">
                                        <button onClick={() => {
                                            if (disputeStep === 0) setPhase('pending');
                                            else setDisputeStep(s => s - 1);
                                        }} className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-gray-100 transition-colors">
                                            <span className="material-icons text-gray-500 text-xl">arrow_back</span>
                                        </button>
                                        <div>
                                            <p className="font-bold text-gray-900 text-sm">Dispute Assistant</p>
                                            <p className="text-xs text-gray-400">Step {disputeStep + 1} of 4</p>
                                        </div>
                                        {/* Step dots */}
                                        <div className="ml-auto flex items-center gap-1.5">
                                            {[0,1,2,3].map(i => (
                                                <div key={i} className={`h-1.5 rounded-full transition-all ${i === disputeStep ? 'w-5 bg-red-500' : i < disputeStep ? 'w-1.5 bg-[#10B981]' : 'w-1.5 bg-gray-200'}`} />
                                            ))}
                                        </div>
                                    </div>

                                    <div className="bg-red-50 border border-red-100 rounded-2xl p-4 flex items-start gap-3">
                                        <span className="material-icons text-red-500 text-lg shrink-0">auto_awesome</span>
                                        <p className="text-xs text-red-800 leading-relaxed font-medium">
                                            AI is guiding you through structured evidence collection to build the strongest case for our review team.
                                        </p>
                                    </div>

                                    <AnimatePresence mode="wait">

                                        {/* Step 0: Category */}
                                        {disputeStep === 0 && (
                                            <motion.div key="ds0" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-4">
                                                <div>
                                                    <p className="text-sm font-bold text-gray-900 mb-3">What is the main issue?</p>
                                                    <div className="space-y-2">
                                                        {DISPUTE_CATEGORIES.map(cat => (
                                                            <button key={cat} type="button"
                                                                onClick={() => setDisputeCategory(cat)}
                                                                className={`w-full text-left px-4 py-3.5 rounded-xl border text-sm font-medium transition-all ${
                                                                    cat === disputeCategory
                                                                        ? 'border-red-400 bg-red-50 text-red-700 ring-2 ring-red-200'
                                                                        : 'border-gray-200 bg-white text-gray-700 hover:bg-gray-50'
                                                                }`}>
                                                                {cat}
                                                            </button>
                                                        ))}
                                                    </div>
                                                </div>
                                                <button
                                                    onClick={() => { setAnswers({}); setDisputeStep(1); }}
                                                    className="w-full py-3.5 bg-[#0F172A] hover:bg-slate-700 text-white font-bold rounded-xl text-sm transition-all flex items-center justify-center gap-2"
                                                >
                                                    Continue <span className="material-icons text-base">arrow_forward</span>
                                                </button>
                                            </motion.div>
                                        )}

                                        {/* Step 1: Guided Questions */}
                                        {disputeStep === 1 && (
                                            <motion.div key="ds1" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-4">
                                                <p className="text-sm font-bold text-gray-900">Help us understand the situation</p>
                                                <div className="space-y-4">
                                                    {(GUIDED_QUESTIONS[disputeCategory] || GUIDED_QUESTIONS['Other']).map((q, i) => (
                                                        <div key={i}>
                                                            <label className="block text-xs font-bold text-gray-500 mb-1.5">{q}</label>
                                                            <textarea
                                                                rows={2}
                                                                value={answers[q] || ''}
                                                                onChange={e => setAnswers(prev => ({ ...prev, [q]: e.target.value }))}
                                                                placeholder="Type your answer…"
                                                                className="w-full px-4 py-3 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-red-200 focus:border-red-400 transition-colors resize-none"
                                                            />
                                                        </div>
                                                    ))}
                                                </div>
                                                <button
                                                    onClick={() => setDisputeStep(2)}
                                                    className="w-full py-3.5 bg-[#0F172A] hover:bg-slate-700 text-white font-bold rounded-xl text-sm transition-all flex items-center justify-center gap-2"
                                                >
                                                    Continue <span className="material-icons text-base">arrow_forward</span>
                                                </button>
                                            </motion.div>
                                        )}

                                        {/* Step 2: Photo Evidence */}
                                        {disputeStep === 2 && (
                                            <motion.div key="ds2" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-4">
                                                <div>
                                                    <p className="text-sm font-bold text-gray-900 mb-1">Do you have photo evidence?</p>
                                                    <p className="text-xs text-gray-400 mb-4">Photos significantly strengthen your case. This step is optional.</p>
                                                    <input ref={evidenceRef} type="file" accept="image/*" className="hidden" onChange={handleEvidenceChange} />
                                                    <div
                                                        onClick={() => evidenceRef.current?.click()}
                                                        className={`border-2 border-dashed rounded-2xl p-8 flex flex-col items-center justify-center cursor-pointer transition-all group ${
                                                            evidencePreview ? 'border-[#10B981] bg-green-50' : 'border-gray-200 hover:border-gray-300 hover:bg-gray-50'
                                                        }`}
                                                    >
                                                        {evidencePreview ? (
                                                            <img src={evidencePreview} alt="Evidence" className="h-36 object-contain rounded-xl mb-2" />
                                                        ) : (
                                                            <>
                                                                <span className="material-icons text-gray-300 text-4xl mb-2 group-hover:text-gray-400 transition-colors">add_photo_alternate</span>
                                                                <p className="text-sm font-semibold text-gray-500">Tap to attach photo</p>
                                                                <p className="text-xs text-gray-400 mt-0.5">PNG, JPG up to 10MB</p>
                                                            </>
                                                        )}
                                                    </div>
                                                </div>
                                                <button
                                                    onClick={handleGenerateSummary}
                                                    disabled={generatingSummary}
                                                    className="w-full py-3.5 bg-red-600 hover:bg-red-700 disabled:opacity-60 text-white font-bold rounded-xl text-sm transition-all flex items-center justify-center gap-2"
                                                >
                                                    {generatingSummary ? (
                                                        <>
                                                            <div className="w-4 h-4 rounded-full border-2 border-white/30 border-t-white animate-spin" />
                                                            Generating Summary…
                                                        </>
                                                    ) : (
                                                        <>
                                                            <span className="material-icons text-base">auto_awesome</span>
                                                            Generate AI Summary
                                                        </>
                                                    )}
                                                </button>
                                                <button
                                                    onClick={handleGenerateSummary}
                                                    disabled={generatingSummary}
                                                    className="w-full py-2 text-xs text-gray-400 hover:text-gray-600 transition-colors"
                                                >
                                                    Skip photos and continue
                                                </button>
                                            </motion.div>
                                        )}

                                        {/* Step 3: AI Summary + Submit */}
                                        {disputeStep === 3 && (
                                            <motion.div key="ds3" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-4">
                                                <div className="flex items-center gap-2 mb-1">
                                                    <span className="material-icons text-[#10B981] text-lg">auto_awesome</span>
                                                    <p className="text-sm font-bold text-gray-900">AI-Generated Dispute Summary</p>
                                                </div>
                                                <div className="bg-gray-50 border border-gray-200 rounded-2xl p-5">
                                                    <pre className="text-xs text-gray-600 whitespace-pre-wrap leading-relaxed font-sans">{generatedSummary}</pre>
                                                </div>
                                                <p className="text-[11px] text-gray-400 leading-relaxed">
                                                    This summary will be sent to our review team along with your account details. Payment is frozen until a resolution is reached.
                                                </p>
                                                <button
                                                    onClick={handleDispute}
                                                    className="w-full py-4 bg-red-600 hover:bg-red-700 text-white font-bold rounded-xl text-sm transition-all shadow-md flex items-center justify-center gap-2"
                                                >
                                                    <span className="material-icons text-base">gavel</span>
                                                    Submit Dispute
                                                </button>
                                            </motion.div>
                                        )}

                                    </AnimatePresence>
                                </motion.div>
                            )}

                        </AnimatePresence>
                    </div>
                </main>

                <MobileNavBar />
            </div>
        </div>
    );
};

export default ConfirmCompletion;
